version: 1
accounts:
- name: exampleWalletKiiBotom
  coins: [ 54000000000000tkii ]
genesis:
  chain_id: kiiventador
  app_state:
    staking:
      params:
        bond_denom: tkii
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: exampleWalletKiiBotom
  bonded: 100000000000tkii
  app:
    pruning: "nothing"
  config:
    moniker: "KiiAventadorBotom"
  client:
    output: "json"